apiVersion: v1
kind: Service
metadata:
  name: my-app-nginx-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # Port on the service
      targetPort: 80   # Port on the container (Nginx is on 80)
      nodePort: 30080  # Port on the node, accessible externally