---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-sample
  template:
    metadata:
      labels:
        app: angular-sample
    spec:
      containers:
      - name: angular-web
        image: angular-sample:latest   # docker build -t angular-sample:latest .
        imagePullPolicy: IfNotPresent   # Don’t try to pull from a registry if it’s local
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: angular-sample
spec:
  type: NodePort
  selector:
    app: angular-sample
  ports:
  - port: 8080        # Cluster‑internal port
    targetPort: 8080  # ContainerPort in your NGINX image
    nodePort: 30001   # Exposes on http://<nodeIP>:30001
