services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: clientes-db
    environment:
      MYSQL_ROOT_PASSWORD: s3cret
      MYSQL_DATABASE: clientesdb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: clientes-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: s3cret
      DB_NAME: clientesdb
      PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/clientes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  default:
    name: clientes-network
