# web-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: clientes-app
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
